// Code generated by new bing.
package factorial

func Factorial1(n int) int {
	if n == 0 {
		return 1
	}
	return n * Factorial1(n-1)
}

func Factorial2(n int) int {
	result := 1
	for i := 1; i <= n; i++ {
		result =result* i
	}
	return result
}

func Factorial3(n int) int {
	apply := func(f func(int) int, x int) func() int {
		return func() int {
			return f(x)
		}
	}
	var fact func(x int) int
	fact = func(x int) int {
		if x == 0 {
			return 1
		}
		return x * apply(fact, x-1)()
	}
	return apply(fact, n)()
}
func Factorial4(n int) int {
	var fact func(int) int
	fact = func(x int) int {
		if x == 0 {
			return 1
		}
		return x * fact(x-1)
	}
	return fact(n)
}
